Recursive directory scan and result summary fix
xlab-si/iac-scan-runner pull request #12
Opened 2022-09-01 00:42 UTC by penenadpi

- added support for recursive subdirectory traversal within IaC archive
- fixed the outputs of several tools (checkstyle, hadolint, htmlhint, ts-lint, es-lint)
- fixed the bug related to additional extensions within Terraform and Tosca archives

2022-09-01 12:22 UTC, cankarm approved these changes
For me it seems OK for now. It would be nice to merge it quick, so we have the fixes covered for the users.

2022-09-01 14:32 UTC, anzoman requested changes
Thanks @penenadpi, here is my review.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/compatibility.py
> +        "other": [""],
Why list with empty string and not just empty list?

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/compatibility.py
> +        scanned_other = []
Do we really need `scanned_<something>`?
I suggest extracting this into a separate object. I see you already have `self.scanned_files`, so you can append directly into that.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/compatibility.py
> +            print(types)
This should probably be removed.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +                return "Passed"
Add a TODO to extract "Passed" and "Problems" into an `Enum` object and use them.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Remove these new empty spaces.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Remove these new empty space.

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/utils.py
> +def file_to_string(file_path: str):
Missing return type.

```suggestion
def file_to_string(file_path: str) -> str:
```

2022-09-01 14:32 UTC, anzoman commented on src/iac_scan_runner/utils.py
> +    except Exception as e:
This exception is probably too broad, try to narrow it down.

2022-09-01 19:51 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        "other": [""],
Ok, gonna fix this one

2022-09-01 19:52 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +            print(types)
I agree, this one remained for debugging. Maybe we should include the adoption of loguru or something similar for next version, could help out a bit.

2022-09-01 19:53 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +                return "Passed"
I agree, should be added

2022-09-01 19:56 UTC, penenadpi commented on src/iac_scan_runner/utils.py
> +def file_to_string(file_path: str):
I definitely forgot to add it, gonna fix it

2022-09-01 19:56 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Ok

2022-09-01 20:06 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Removed

2022-09-01 20:07 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        scanned_other = []
Would work on that later, as code would need to be quite refactored

2022-09-02 06:57 UTC, anzoman approved these changes
@penenadpi thanks for your contribution, let's merge this one!

2022-09-02 06:57 UTC, merged