Scan results persistence into Mongo DB
xlab-si/iac-scan-runner pull request #13
Opened 2022-09-06 09:31 UTC by penenadpi

After applying this set of changes, we get the following features:
- Mongo DB instance run in Docker container, spawned at startup
- scan result persistence into Mongo DB
- API to listing and deleting scan results
- cron job for removal of old scan results (more than 14 days)

2022-09-06 12:17 UTC, anzoman requested changes
Thanks @penenadpi, here are my first comments.

2022-09-06 12:17 UTC, anzoman commented on install-checks.sh
> +    sudo docker run --name scannerdb -d -p 27017:27017 mongo
This should be runnable without sudo, so remove it.

2022-09-06 12:17 UTC, anzoman commented on requirements.txt
> +schedule==1.1.0
Also add these packages to `setup.cfg`.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/api.py
>  # create an API instance
Organize imports. There should be blank lines between imports and the code.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/api.py
> +
I would rather introduce only those two endpoints:

- `GET /results/` - retrieves all results by default and if params (UUID) are set it filters them
- `DELETE /results` - deletes results (make sure that you use `app.delete` here)

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/cleanup_old_scans.py
> +#schedule.every().day.at("08:54").do(periodic_clean_job)
Remove any commented code.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/cleanup_old_scans.py
> +        print(doc["time"])
This is probably not needed.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/cleanup_old_scans.py
> +        if(age>14):
Reformat code to add spaces before and after operators.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """
Start all comments in new row like this (as it's clearer):

```suggestion
        """
        Inserts new scan result into database
        :param result: Dictionary holding the scan summary
        """         
```

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Shows scan result with given id
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Deletes the scan result with given id from database
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Shows all the scan records from the database
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Calculates how many days have passed between today and given timestamp
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Calculates how long a scan result resides in database since its insertion
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        """Calculates how long a scan result resides in database since its insertion
Start comment in new row.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "Problems":
Reformat code.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "Passed":
Reformat code.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "No files" :
Reformat code.

2022-09-06 12:17 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            self.results_summary.outcomes["time"]=datetime.now().strftime("%m/%d/%Y, %H:%M:%S")
Reformat code (operators should have space before and after).

2022-09-09 08:33 UTC, penenadpi commented on requirements.txt
> +schedule==1.1.0
Should I provide versions as well, or only list them 
pymongo
schedule

This is my doubt

2022-09-09 08:34 UTC, penenadpi commented on src/iac_scan_runner/api.py
>  # create an API instance
Added

2022-09-09 08:35 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +            self.results_summary.outcomes["time"]=datetime.now().strftime("%m/%d/%Y, %H:%M:%S")
Fixed

2022-09-09 08:36 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "No files" :
Fixed

2022-09-09 08:36 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "Passed":
Fixed

2022-09-09 08:36 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and self.outcomes[scan]["status"] == "Problems":
Fixed

2022-09-09 08:37 UTC, penenadpi commented on install-checks.sh
> +    sudo docker run --name scannerdb -d -p 27017:27017 mongo
On my PCs, it requires sudo for that. It might be that docker configuration has to be modified?

2022-09-09 08:38 UTC, penenadpi commented on src/iac_scan_runner/cleanup_old_scans.py
> +        print(doc["time"])
Removed

2022-09-09 08:38 UTC, penenadpi commented on src/iac_scan_runner/cleanup_old_scans.py
> +        if(age>14):
Modified

2022-09-09 08:45 UTC, penenadpi commented on src/iac_scan_runner/cleanup_old_scans.py
> +#schedule.every().day.at("08:54").do(periodic_clean_job)
Deleted the comments and left only the necessary code

2022-09-09 08:46 UTC, penenadpi commented on requirements.txt
> +schedule==1.1.0
Please check it out

2022-09-09 08:57 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +
Fixed the delete results

2022-09-09 12:59 UTC, anzoman commented on install-checks.sh
> +    sudo docker run --name scannerdb -d -p 27017:27017 mongo
Yes indeed, we should not use `sudo` by default so remove it, users should take care of having docker accessible by the current user.

2022-09-09 13:00 UTC, anzoman commented on requirements.txt
> +schedule==1.1.0
The versions should be there, because if you don't specify them it will use the latest one and then anything can break. However, we should take care of keeping these version up to date.

2022-09-09 13:02 UTC, anzoman commented on src/iac_scan_runner/api.py
> +
I also recommend having simple endpoints (e.g., `results`) as I suggested in https://github.com/xlab-si/iac-scan-runner/pull/13#discussion_r963626158.

2022-09-09 13:39 UTC, penenadpi commented on install-checks.sh
> +    sudo docker run --name scannerdb -d -p 27017:27017 mongo
Ok, I removed it

2022-09-09 14:24 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +
Take a look

2022-09-19 11:08 UTC, anzoman requested changes

2022-09-19 11:08 UTC, anzoman commented on setup.cfg
> +  schedule==1.1.0
Update to:

```suggestion
  pymongo == 4.2.0
  schedule == 1.1.0
```

2022-09-19 11:26 UTC, penenadpi commented on install-checks.sh
> +}
Will be added

2022-09-19 11:28 UTC, penenadpi commented on setup.cfg
> +  schedule==1.1.0
Done

2022-09-19 12:48 UTC, anzoman approved these changes

2022-09-19 12:49 UTC, merged