Fixed output for scenario when there is no list of desired scans
xlab-si/iac-scan-runner pull request #15
Opened 2022-09-07 23:01 UTC by penenadpi

After applying this fix, errors due to presence of compatibility matrix feature presence in case of no scan tools listed as argument will be avoided.

2022-09-08 06:56 UTC, anzoman requested changes
@penenadpi thanks for this fix, there is just a few things to address.

2022-09-08 06:56 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                        print(iac_check.name)
Remove any unnecessary prints.
This could go to logs when we establish them in the future.

2022-09-08 06:56 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +
This change should probably go into a separate commit.

2022-09-08 06:56 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        print(compatible_checks)
Remove.

2022-09-08 06:56 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            print("Else")
Remove.

2022-09-08 08:24 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                        print(iac_check.name)
Removed all the print statements. Would add loguru in next release.

2022-09-08 08:24 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +
I would keep it here, as it also fixes the issue related to errors in some cases

2022-09-08 08:25 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +            print("Else")
Removed

2022-09-08 10:29 UTC, penenadpi commented
I added some fixes, please take a look

2022-09-09 12:57 UTC, anzoman requested changes

2022-09-09 12:57 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        if selected_checks and selected_checks!="":
This if already checks if `selected_checks` is not empty string, because non empty string enforces True value, so you can keep this as it is.

2022-09-09 12:57 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Fix this indentation.

2022-09-12 09:03 UTC, merged