Improved connection error handling for MongoDB interface
xlab-si/iac-scan-runner pull request #18
Opened 2022-09-20 13:02 UTC by penenadpi

- Fixed error handling in case of non-working Mongo DB instance or any other connection error.
- Added support for disabling persistence manually

2022-09-21 09:37 UTC, anzoman requested changes

2022-09-21 09:37 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        return JSONResponse(status_code=status.HTTP_400_BAD_REQUEST, content=str(e))
Remove and put this logic when the IaC Scan Runner is starting.

2022-09-21 09:37 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            connection_string = os.environ['MONGO_STRING']
Rename connection string env var to something like `MONGODB_CONNECTION_STRING`.

2022-09-21 09:37 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            print(connection_string)
Remove.

2022-09-21 09:37 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            self.mycol = self.mydb["results"]
Check if this can be somehow validated.

2022-09-22 08:07 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +        return JSONResponse(status_code=status.HTTP_400_BAD_REQUEST, content=str(e))
Done, moved to pre-start checks and used environment variable instead for turning it on/off

2022-09-22 08:08 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +            connection_string = os.environ['MONGO_STRING']
Done

2022-09-22 08:08 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +            print(connection_string)
Done

2022-09-22 08:08 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +            self.mycol = self.mydb["results"]
Added checks if connection worked and objects are not None

2022-09-22 11:44 UTC, anzoman requested changes

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        if(uuid and uuid!=""):
```suggestion
        if uuid:           
```

Formatting is needed here, and also empty string is alreafy treated as False.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/api.py
> +async def get_scan_result(uuid: Optional[str]) -> JSONResponse:
What happens when UUID is not set?

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/api.py
>      :param uuid: Identifier of a scan record in database
I would mention database in the API, just `Identifier of saved scan record`.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +
Too many blank lines.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +
Remove unnecessary blank line.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            connection_string = os.environ['MONGODB_CONNECTION_STRING']
Validate that `connection_string ` is None if `MONGODB_CONNECTION_STRING` not set.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +        except Exception as e:
Can you narrov that down to a more specific Exception.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +                return str(x)
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            mydoc = self.mycol.delete_one(myquery)
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            return output
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +            return self.days_passed(scan_ts)
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +                    self.delete_result(doc_uuid)
Formatting needed.

2022-09-22 11:44 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            self.persistence_enabled = False
Formatting needed. Also remove prints.

2022-09-22 12:34 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +
Deleted

2022-09-22 12:34 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +
Done

2022-09-22 12:37 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +            self.persistence_enabled = False
Deleted and fixed formatting

2022-09-22 12:43 UTC, penenadpi commented on src/iac_scan_runner/results_persistence.py
> +        except Exception as e:
Gonna put this as TODO, there are many possible exceptions to be considered here

2022-09-23 07:14 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        if(uuid and uuid!=""):
Remove all redundant parentheses.

2022-09-23 07:20 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        if(uuid and uuid!=""):
Will be resolved later.

2022-09-23 08:54 UTC, anzoman approved these changes
Thanks @penenadpi for your contributions and let's merge this one!

2022-09-23 08:55 UTC, merged