Improved user-relevant info visulization
xlab-si/iac-scan-runner pull request #19
Opened 2022-09-22 12:02 UTC by penenadpi

Additional fields are added to the generated HTML web page:
- archive name
- timestamp when the run was initiated
- execution duration
- final verdict, if all the checks passed or some problems were detected

2022-09-29 07:52 UTC, anzoman requested changes

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +    def evaluate_verdict(self):
Missing docstring.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if(check!="uuid" and check!="time" and check!="problems" and check!="passed" and check!="total"):
Format all ifs in the following way:

```python
if something == "babla":
    code
```

Because there is no need for parentheses and there should be spaces between operators.
Otherwise the code would look to much like C to me.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +                #print(self.outcomes[check]["status"])
Remove.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +
Too many blank lines.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan == "uuid") and not(scan == "time") and not(scan == "archive") and not(scan == "execution-duration")  and not(scan == "verdict") and self.outcomes[scan]["status"] == "Problems"
Reformat.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan == "uuid") and not(scan == "time") and not(scan == "archive") and not(scan == "execution-duration") and not(scan == "verdict") and self.outcomes[scan]["status"] == "Passed":
Reformat.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and not(scan == "archive") and not(scan == "execution-duration")  and not(scan == "verdict") and self.outcomes[scan]["status"] == "Info" :
Reformat.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and not(scan == "archive") and not(scan == "execution-duration")  and not(scan == "verdict") and self.outcomes[scan]["status"] == "No files" :
Reformat.

2022-09-29 07:52 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            self.results_summary.outcomes["archive"] = self.archive_name
Reformat - remove hanging spaces.

2022-09-29 08:11 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +    def evaluate_verdict(self):
Added

2022-09-29 13:01 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if not(scan=="uuid") and not(scan=="time") and not(scan == "archive") and not(scan == "execution-duration")  and not(scan == "verdict") and self.outcomes[scan]["status"] == "No files" :
The same

2022-09-29 13:01 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if not(scan == "uuid") and not(scan == "time") and not(scan == "archive") and not(scan == "execution-duration")  and not(scan == "verdict") and self.outcomes[scan]["status"] == "Problems"
Done

2022-09-29 13:03 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +                #print(self.outcomes[check]["status"])
Done

2022-09-29 13:04 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if(check!="uuid" and check!="time" and check!="problems" and check!="passed" and check!="total"):
Fixed

2022-09-30 09:35 UTC, anzoman approved these changes

2022-09-30 09:35 UTC, merged