Scan project persistence
xlab-si/iac-scan-runner pull request #21
Opened 2022-09-28 23:13 UTC by penenadpi

- Assigning projects to persisted scan run results
- API to add generate new project or assign configuration (expanded in future)

2022-09-29 07:59 UTC, anzoman requested changes

2022-09-29 07:59 UTC, anzoman commented on examples/projects_example.py
> +
Is there too many blank lines?

2022-09-29 07:59 UTC, anzoman commented on examples/projects_example.py
> +
Too many blank lines.

2022-09-29 07:59 UTC, anzoman commented on examples/test_scanner_simple.py
> +par = { "projectid" : (None, "penenadpi") }
Reformat.

```suggestion
par = { 
    "projectid" : (None, "penenadpi") 
}
```

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        print(projectid)
Remove prints.

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/api.py
> +            projectid=""
Reformat:

```suggestion
            projectid = ""
```

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/api.py
> +            projectid=""
Also how does this change the value of `project_id`. Empty string `""` is still considered as `False`.

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/api.py
> +@app.post("/new_project", summary="Retrieve particular scan result by given uuid", responses={200: {}, 400: {"model": str}})
Retrieve particular scan result by given uuid? Is that what this API endpoint really does?
Shouldn't it be "Create a new project" or something?

Update docstring and summary.

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/api.py
> +@app.post("/set_project_config", summary="Retrieve particular scan result by given uuid", responses={200: {}, 400: {"model": str}})
Update docstring and summary.

2022-09-29 07:59 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +        return "Passed"
Aren't those changes from #19?
If they are this PR should be a draft and there should be a note that we should first reveiw and merge #19 and then proceed with this one.

2022-09-29 12:24 UTC, penenadpi commented on examples/projects_example.py
> +
I have deleted them

2022-09-29 12:24 UTC, penenadpi commented on examples/projects_example.py
> +
Also deleted

2022-09-29 12:24 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +        print(projectid)
Done

2022-09-29 12:26 UTC, penenadpi commented on examples/test_scanner_simple.py
> +par = { "projectid" : (None, "penenadpi") }
Done

2022-09-29 12:35 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +@app.post("/set_project_config", summary="Retrieve particular scan result by given uuid", responses={200: {}, 400: {"model": str}})
Updated

2022-09-29 12:36 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        return "Passed"
Yes, I will add the Draft prefix and also resolve #19 . We should merge this after #19

2022-09-29 12:37 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +            projectid=""
To make sure it is an empty string before inserting into DB

2022-09-30 11:00 UTC, anzoman approved these changes

2022-09-30 11:00 UTC, merged