Project configuration and parameter persistence
xlab-si/iac-scan-runner pull request #22
Opened 2022-10-05 12:17 UTC by penenadpi

Added initial capabilities related to storage and retrieval of project configuration parameters:
- ProjectConfig class for persistence of project configurations
- Simple API for new configuration creation and setting parameters

2022-10-05 13:17 UTC, anzoman requested changes

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/api.py
> +
Uneeded space.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            connection_string = os.environ['MONGODB_CONNECTION_STRING']
Rather use:

```suggestion
            connection_string = os.getenv("MONGODB_CONNECTION_STRING", None)
```

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            if(connection_string):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +                self.mycol = self.mydb["configs"]
Are these `scandb` and `configs` fixed or have to have these names?

I suppose not and if so add a TODO to extract these in a separate object or variable.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            print(str(e))
You can simplify:

```suggestion
            print(f"Configuration persistence not available, error: {e}")
```

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        return json.loads(json_util.dumps(data))
I'd wrap this in a try-catch block as JSON errors wile loading/dumping are quite common.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.connection_problem == True):
Formatting (missing spaces). Also omit `== True`

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Formatting (missing spaces). Also checking that something is not None should be done with `if x is not None`.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +
Remove this space.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        config_json["creatorid"] = creatorid
Add a TODO to extract this into a separate object/variable.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(parameters):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.connection_problem == True):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.connection_problem==True):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Use `is not None` everywhere.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +    def load_config(self, configid: str):
Specify function return type.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.connection_problem == True):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +                print(str(e))
Print also a description of this error.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.connection_problem==True):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Use `is not None`.

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
What are those spaces for?

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        if(self.users_enabled):
Formatting (missing spaces).

2022-10-05 13:17 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Remove this uneeded empty line.

2022-10-05 22:50 UTC, penenadpi commented on examples/configs_example.py
> +parameters["user"]="user"
Done

2022-10-05 22:53 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Done

2022-10-05 22:53 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +        if(self.users_enabled):
Modified

2022-10-05 22:54 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Deleted

2022-10-05 22:54 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Done

2022-10-05 22:55 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
Resolved

2022-10-05 22:59 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +                print(str(e))
Message added

2022-10-06 09:34 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +
Done

2022-10-06 09:36 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +            connection_string = os.environ['MONGODB_CONNECTION_STRING']
Would still prefer this one, but gonna fix all the error handling and exceptions in another pull request

2022-10-06 09:37 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +            if(connection_string):
fixed

2022-10-06 09:40 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +            print(str(e))
Done

2022-10-07 10:21 UTC, anzoman requested changes

2022-10-07 10:21 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        cid=project_config.new_config(creatorid, None)
Apply code formatting (missing spaces).

2022-10-07 10:21 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        if(creatorid):
Apply code formatting (missing spaces).

2022-10-07 22:02 UTC, penenadpi commented on src/iac_scan_runner/api.py
> +        if(creatorid):
Corrected

2022-10-11 11:55 UTC, anzoman requested changes

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +
Unnecessary space.

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            print("Could not parse JSON, error: {e}")
This won't print exception, but this will:

```suggestion
            print(f"Could not parse JSON, error: {e}")
```

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +
Unnecessary newline.

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        # TODO:Add this names into object
```suggestion
        # TODO: Add this names into object
```

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +
Correct others as well.

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            myquery = { "configid": configid }
```suggestion
            myquery = {"configid": configid}
```

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +                print("Could not update project configuration {configid} error: {e}")
```suggestion
                print(f"Could not update project configuration {configid} error: {e}")                
```

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +            new_value = { "$set": { "parameters": parameters } }
What is this `$set`?

2022-10-11 11:55 UTC, anzoman commented on src/iac_scan_runner/scan_project.py
> +        if(self.connection_problem==True):
Formatting (spaces).

2022-10-11 12:01 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +            new_value = { "$set": { "parameters": parameters } }
This is part of pymongo syntax for update command (what will actually be updated) against matched documents according to myquery

2022-10-11 12:32 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +
Done

2022-10-11 12:33 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +            print("Could not parse JSON, error: {e}")
Fixed

2022-10-12 13:17 UTC, anzoman requested changes

2022-10-12 13:17 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol is not None):
There are still a lot of these kind of formatting errors. Please go through the code and refactor them all.

```suggestion
        if self.mycol is not None:          
```

2022-10-12 13:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
>                  if(age>14):
This number is hardcoded, add a TODO to introduce env var to configure it.

2022-10-12 13:17 UTC, anzoman commented on src/iac_scan_runner/results_persistence.py
> +
Remove all unnecessary spaces between function signature and docstring.

2022-10-12 13:17 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        dir_name = "../outputs/logs/scan_run_" + random_uuid
Add a TODO as this path should not be hardcoded.

2022-10-12 13:17 UTC, anzoman commented on src/iac_scan_runner/api.py
> +        print(parameters)
Remove any prints that are still left.

2022-10-12 14:47 UTC, penenadpi commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol is not None):
Fixed

2022-10-13 07:31 UTC, anzoman commented on src/iac_scan_runner/project_config.py
> +        if(self.mycol != None):
This has not been updated.

2022-10-14 13:22 UTC, anzoman approved these changes
Thank you @penenadpi!

2022-10-14 13:22 UTC, merged