Check list enable/disable persistence support
xlab-si/iac-scan-runner pull request #23
Opened 2022-10-18 23:07 UTC by penenadpi

Applying this commit:
- support for check enable/disable as part of persistent project configuration

2022-10-21 14:01 UTC, anzoman requested changes

2022-10-21 14:01 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
There is a lot of new code starting with this line. Could you extract it to a separate function?

2022-10-21 14:01 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
This line can be removed.

2022-11-04 17:23 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Fixed

2022-11-04 17:35 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +            if check != "uuid" and check != "time" and check != "problems" and check != "passed" and check != "total" and check != "execution-duration" and check != "projectid" and check!="archive":
Wrote a new function checking if string is not in a list

2022-11-04 17:36 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +
Gonna do it for next MR

2022-11-05 21:24 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                        self.results_summary.summarize_outcome(selected_check, scan_output[check.name]["output"], self.compatibility_matrix.scanned_files, Compatibility.compatibility_matrix)
Should be fine now, as I split it into several lines in each similar case with more than 120 chars.

2022-11-07 08:12 UTC, anzoman approved these changes

2022-11-07 08:12 UTC, merged