Penenadpi/result filter
xlab-si/iac-scan-runner pull request #7
Opened 2022-07-29 10:18 UTC by penenadpi

Added features related to dumping logs, summarization and visualization of check outcomes:
- Compatibility class, which provides dictionary of compatible checks for particular type of files. Therefore, we would only perform checks that make sense for given types of files present within the uploaded IaC directory [work in progress, should be extended to cover all cases]
- ResultsSummary class, which is responsible for summarizing and visualizing the results in two forms:
   1. JSON file - result found in src/json_dumps
   2. HTML web page - the check results are sorted in three categories as table - Problems ; Passed.; No Files - nothing was actually scanned, as there are no compatible files - results found in src/generated_html. The results asre sorted, so problematic checks are shown in red color first, then passed checks in green, and grayed out scans that were skipped. 
  Both files hold the following info: 1) check name 2) outcome of check - Pass/Problems/No Files 3)list of scanned files 4) log generated by the corresponding scanner tool

In order to run a demo, you can run src/iac_scan_runner/test/test_scanner_simple.py using CLI which makes use of REST API, by sending a POST request taking the given parameters

python3 test_scanner_simple.py tf1.zip tflint,tfsec,checkstyle

2022-07-29 10:53 UTC, cankarm commented on src/json_dumps/1658820632.92485.json
> +{"tflint": true, "tfsec": true}
Does it make sense to have these temporary files in the repository? We could have some of them as documentation example, but not here.

2022-07-29 10:53 UTC, cankarm commented on src/scan_run_1658820632.92485/tfsec.txt
> +[0m[0m  [34mtimes[39m
I expect that this is also temporary file?

2022-07-29 10:54 UTC, cankarm commented
@anzoman, can you review and cover merging of this PR?

2022-08-01 09:32 UTC, anzoman requested changes
Thanks @penenadpi for your valuable contribution!

I have made some comments that should be addressed.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Optimize all imports in this file (`Ctrl-Alt-O` if you are using PyCharm).

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        # This matrix should be revised and extended, it is just a proof of concept here as for now
TODOs should be marked as the IDE will mark them too.

```suggestion
        # TODO: This matrix should be revised and extended, it is just a proof of concept here as for now
```

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        }
Again these names for checks should not be hardcoded strings but rather specified as a static property of a corresponding check class (i.e., `AnsibleLintCheck.name`).

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        self.results_summary = ResultsSummary()
Instance attributes `checker` and `results_summary` are defined outside `__init__`, which is not the best practice. Consider moving them to  `__init__` and create them there.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            sonar_scanner.name: sonar_scanner,
This ending comma looks weird (but Python allows it) as if I am expecting something but it is not there or someone has forgotten to add it. I would remove it and add it on the way when we supply new checks.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +    ) -> Union[dict, str]:
This could stay an one-liner:

```suggestion
    def _run_checks(self, selected_checks: Optional[List], scan_response_type: ScanResponseType) -> Union[dict, str]:
```

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                print(check)
These should be erased, if we need some logging we could add it later.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                        print("NO SCAN")
Remove.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            print(non_compatible_checks)
Those prints are probably not needed?

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                        )
I would not hardcode `"output"`, but rather call an `output` property of `CheckResult`.

```suggestion
                        write_string_to_file(check.name, dir_name, scan_output[selected_check].output)
```

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +    ) -> str:
This could stay an one-liner. The line break is set at 120 characters.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                    ) as config_file_local:
Hmm are you using any special formatter? Just because all one lines were extended to multiple lines. This is okay (although I don't like to to something that you can do in one line in multiple lines, except when line limit is low like in PEP8 that uses 79 characters) but we should keep the code in the same style over the whole repository, so if you intent to reformat everything we could do it but in a separate PR.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                )
See the comment about formatting.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        )
See the comment about formatting.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +            )
See the comment about formatting.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/test/test_scanner_simple.py
> +print(scan_result)
I like this as it is a start for https://github.com/xlab-si/iac-scan-runner/issues/1.

But I would move the tests out of the `src` folder. For the reference, you can look up how we did this in [`xopera-opera`](https://github.com/xlab-si/xopera-opera) repository.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/utils.py
> +        )
See the comment about formatting.

2022-08-01 09:32 UTC, anzoman commented on src/iac_scan_runner/utils.py
>          )
See the comment about formatting.

2022-08-01 09:32 UTC, anzoman commented on src/json_dumps/1658820632.92485.json
> +{"tflint": true, "tfsec": true}
I am wondering about the same and would remove these files. However, you can still attach them to the description of this PR.

2022-08-01 09:32 UTC, anzoman commented on src/scan_run_1658820632.92485/tfsec.txt
> +[0m[0m  [34mtimes[39m
This file (`src/scan_run_1658820632.92485/tfsec.txt`), as well as `src/scan_run_1658820632.92485/tflint.txt`, should be removed, but you, you can still attach them both to the description of this PR to showcase what result we actually expect to see.

2022-08-07 10:28 UTC, penenadpi commented on src/generated_html/1658820632.92485.html
> +<!DOCTYPE html> <html> <style> table, th, td { border:1px solid black;}</style> <body> <h2>Scan results</h2> <table style='width:100%'> <tr> <th>Scan</th><th>Outcome</th><th>Files</th> </tr><tr><td>t
The example of the generated output is from the version with much less info and other naming of the outcomes. Outcome refers to final verdict of a single scanning tool when executed against a compatible set of files. Therefore, I will delete the HTML file and include the current version of the output generated by tool within the readme or additional document,.

2022-08-07 10:31 UTC, penenadpi commented on src/iac_scan_runner/test/test_scanner_simple.py
> +print(scan_result)
When looking into xopera, I would say that my test lies more under example category, so I would put it under examples directory instead of tests. The tests would contain something more alike unit tests, but this one just demonstrates the new features and capabilities.

2022-08-07 10:32 UTC, penenadpi commented on src/scan_run_1658820632.92485/tfsec.txt
> +[0m[0m  [34mtimes[39m
These are log outputs of distinct scanning tools. I will delete them from repo.

2022-08-07 10:33 UTC, penenadpi commented on src/json_dumps/1658820632.92485.json
> +{"tflint": true, "tfsec": true}
This one is also outdated version of summary, as the latest code produces more sophisticated one. Gonna remove it as well.

2022-08-07 10:33 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        :param iac_dircetory: Extracted iac archive path"
Gonna correct this and all the similar ones.

2022-08-07 10:35 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        # parse scans
No, probably the black linter messed it up

2022-08-07 10:36 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +        # This matrix should be revised and extended, it is just a proof of concept here as for now
Ok, this one is really to be extended, so it lies under TODO category

2022-08-07 10:38 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +            print(non_compatible_checks)
They were here only for debug purposes, definitely gonna remove them

2022-08-07 10:38 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +    ) -> str:
Probably black linter for Python broke it into multiple lines

2022-08-07 10:39 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                    ) as config_file_local:
I was using black linter for python. If you have some other suggestion auto formatter, please let me know.

2022-08-07 10:40 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                print(check)
I agree, these prints were here only for debug purposes.

2022-08-07 10:40 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +    ) -> Union[dict, str]:
Probably black linter messed it up

2022-08-07 10:41 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +            sonar_scanner.name: sonar_scanner,
I gonna remove it

2022-08-07 10:42 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +    ) -> str:
Ok, gonna add it

2022-08-07 10:43 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        print(checks_list)
Ok, as for now I can remove them, they were only here for debugging.

2022-08-07 10:44 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        scanned_html = list()
Ok, gonna do it

2022-08-07 10:45 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +    def get_check_list(self, iac_type: str) -> list:
Ok, gonna do it everywhere if it is possible to specify the strict type of the list when it comes to elements.

2022-08-11 13:06 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +    def get_check_list(self, iac_type: str) -> list:
Done as you suggested.

2022-08-11 13:06 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        print(checks_list)
Removed them as you suggested

2022-08-11 13:07 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        html = False
I removed the variables together with the comments where they were included

2022-08-11 13:08 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        scanned_html = list()
Swapped list() with square brackets, as you suggested

2022-08-11 13:08 UTC, penenadpi commented on src/generated_html/1658820632.92485.html
> +<!DOCTYPE html> <html> <style> table, th, td { border:1px solid black;}</style> <body> <h2>Scan results</h2> <table style='width:100%'> <tr> <th>Scan</th><th>Outcome</th><th>Files</th> </tr><tr><td>t
Removed the examples from repo. Gonna add the examples into documentation later.

2022-08-11 13:09 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +                        # and (terraform is False):
I removed the comments, as they were not necessary, neither todo

2022-08-11 13:10 UTC, penenadpi commented on src/iac_scan_runner/test/test_scanner_simple.py
> +print(scan_result)
I changed the directory heirarchy, by removing the test from src, but adding the script to examples on top level of hierarchy

2022-08-11 13:11 UTC, penenadpi commented on src/scan_run_1658820632.92485/tfsec.txt
> +[0m[0m  [34mtimes[39m
I removed it

2022-08-11 13:11 UTC, penenadpi commented on src/json_dumps/1658820632.92485.json
> +{"tflint": true, "tfsec": true}
Removed

2022-08-11 13:14 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        :return: list object conatining string names of checks
Done

2022-08-11 13:15 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        :param matrix: dictionary of available checks for given Iac type
Done

2022-08-11 13:38 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +from iac_scan_runner.utils import write_html_to_file
Removed import os

2022-08-11 14:03 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        self.outcomes[check] = {}
Fixed

2022-08-11 14:11 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        outcomes[check_name]["status"] = outcome
Fixed

2022-08-12 08:29 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        if check == "tfsec":
I would put this as TODO for now and refactor it in next iteration of changes

2022-08-12 09:05 UTC, penenadpi commented on src/iac_scan_runner/results_summary.py
> +        if check == "tfsec":
There are many other changes that I would prefer to finish first, and then switch to this one

2022-08-12 09:22 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                        )
Would resolve that later

2022-08-17 12:26 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +        if check == "tfsec":
Ok, you can create a TODO and we'll implement it in a separate PR.

2022-08-18 11:16 UTC, anzoman requested changes
@penenadpi thanks for updating the PR and resolving most of the issues!
Here are some additional requests for changes, but most of them are TODOs that you need to add to the code.

After you finish with fixes, the next task will be to reorganize your commits. There are now 36 commits in this PR, which is waaaaaay to much for just 354 additions. I suggest refactoring into three commits: adding compattibility matrix, add results summary and incorporating both functionalities into scan runner.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        self.checker = Compatibility()
Why is that param not called `compatibility` or `compatibility_matrix`? The `checker` does not seem to be very expresive.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        dir_name = "../outputs/logs/scan_run_" + random_uuid
Add a TODO to replace this hardcoded path with a parameter.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +        non_compatible_checks = list()
This looks nicer:

```suggestion
        non_compatible_checks = []
```

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Unnecessary new line.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                            scan_output += f"### {selected_check} ###\n{check_output.to_string()}\n\n"
These `###` look weird.
But you can keep them for now and add a TODO to discuss this ouptut foramatting.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +
Unnecessary blank line.

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                            f"### {iac_check.name} ###\n{check_output.to_string()}\n\n"
Add a TODO: Discuss the format of this output

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/utils.py
> +        text_file.write(output_value)
TODO: Wrap this in a try-except block

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/utils.py
> +        text_file.write(output_value)
TODO: Wrap this in a try-except block

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/scan_runner.py
> +                    with open(
TODO: Wrap this in a try-except block

2022-08-18 11:16 UTC, anzoman commented on src/iac_scan_runner/results_summary.py
> +            json.dump(self.outcomes, fp)
TODO: Wrap this in a try-except block

2022-08-18 11:21 UTC, penenadpi commented on outputs/generated_html/README
> +Generated HTML pages are stored here
Yes, this folder is necessary, as it will hold the outputs of code generation

2022-08-18 11:22 UTC, penenadpi commented on outputs/json_dumps/README
> +JSON scan summaries are stored here
I will take a look

2022-08-18 11:22 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        "js": ["es-lint"],
I will add it as well, also other tools which are missing.

2022-08-18 19:44 UTC, penenadpi commented on outputs/generated_html/README
> +Generated HTML pages are stored here
Fixed the automatic creation in install_checks instead

2022-08-18 19:44 UTC, penenadpi commented on outputs/logs/README
> +Individual scan tool logs are dumped here
Done

2022-08-18 19:45 UTC, penenadpi commented on examples/test_scanner_simple.py
> +print(scan_result)
Gonna delete it

2022-08-19 06:44 UTC, penenadpi commented on src/iac_scan_runner/compatibility.py
> +        "js": ["es-lint"],
Added

2022-08-19 06:54 UTC, penenadpi commented on src/iac_scan_runner/scan_runner.py
> +                    with open(
This a part of code which I have not written. but I think it has 
                raise Exception(f'Check: {check_name} is disabled. You need to enable it first.')

2022-08-22 12:15 UTC, anzoman approved these changes
@penenadpi it's okay now.

Many thanks for your first contribution!

2022-08-22 12:16 UTC, merged