Add SAST to the code base
xlab-si/iac-scan-runner pull request #88
Opened 2023-06-19 10:35 UTC by RedekG

For SAST following tools were added:

- flake
- mypy
- bandit
- pylint

This closes #26

2023-06-29 12:52 UTC, anzoman requested changes
Thanks, @RedekG, looks good. I just have some comments that we need to address.

2023-06-29 12:52 UTC, anzoman commented on .pylintrc
> +                         Exception
Missing newline.

2023-06-29 12:52 UTC, anzoman commented on requirements-dev.txt
> +pylint==2.15.4
Please verify that these dev requirements versions are the latest ones (i.e., I know that `pytest` is at `7.4.0` now) and run the lining phase again.

2023-06-29 12:52 UTC, anzoman commented on .pylintrc
> +          fixme
Check if we can remove any of these. For instance, if we don't have any `FIXME` in the code we can remove `fixme` and `pylint` will still go through.

2023-06-29 12:52 UTC, anzoman commented on .flake8
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D205,D301,D402,E731
Do we really have to ignore all these? Please check - ideally, we should not ignore much.

2023-06-29 18:04 UTC, RedekG commented on .pylintrc
> +                         Exception
Fixed.

2023-06-29 18:05 UTC, RedekG commented on requirements-dev.txt
> +pylint==2.15.4
Updated the versions.

2023-06-29 18:05 UTC, RedekG commented on .pylintrc
> +          fixme
I cleared ones that we don't need.

2023-06-29 18:07 UTC, RedekG commented on .flake8
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D205,D301,D402,E731
I cleared this too but following will remain:

D301 - If we use r"""""", function parameters will be shown in swagger UI. 
D205 - Error caused by \f  between summary line and description. 
D107 - No need to have docstring in init.
D104 - No need to have docstring in public package aka. __init__.py
D100 - No need to have docstring in public module

2023-07-04 08:39 UTC, anzoman commented on .flake8
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D205,D301,D402,E731
Okay, then let's keep `D301` and `D205`.

`D100`, `D104`, and `D107` can be quickly resolved by just removing these unneeded docstrings.

2023-07-04 10:34 UTC, anzoman approved these changes
Thanks @RedekG, looks okay, let's merge this one!

2023-07-04 10:34 UTC, merged

2023-07-04 10:34 UTC, cankarm commented
Even though that all review request are being met, the Git says that still some changes need to be made. Can you check this @RedekG?